import { useCallback, useEffect, useState } from "react";
import {
  BedrockStatus,
  CustomerInsights,
  fetchBedrockStatus,
  fetchCustomerInsights,
} from "../api";
import InsightActionModal from "./InsightActionModal";

type Props = {
  customerId: number;
  churnTier?: string | null;
};

type OpenAction = {
  recommendation: string;
  source: "recommendation" | "experience_note";
};

function insightSubtitle(
  insights: CustomerInsights | null,
  bedrockStatus: BedrockStatus | null,
  loading: boolean,
): string {
  if (loading && !insights) {
    if (bedrockStatus?.configured) {
      return "Calling Amazon Bedrock with this customer's warehouse and interaction data…";
    }
    return "Generating guidance with the built-in local advisor (Bedrock is not configured).";
  }
  if (!insights) {
    return "Actionable recommendations can open a draft from account data; send is simulated in this demo.";
  }
  if (insights.source === "bedrock") {
    const model = insights.model_id ? ` (${insights.model_id})` : "";
    return `These insights were generated by Amazon Bedrock${model} from this customer's profile, policies, interactions, and churn score.`;
  }
  if (insights.bedrock_configured) {
    return "Showing the local advisor for this response — Bedrock is configured but was not used (cached fallback or a temporary Bedrock error). Try Refresh insights.";
  }
  return "Showing the built-in local advisor. Configure AWS credentials and CUSTOMER360_BEDROCK_* variables to use Amazon Bedrock.";
}

export default function CustomerInsightsPanel({ customerId, churnTier }: Props) {
  const [insights, setInsights] = useState<CustomerInsights | null>(null);
  const [bedrockStatus, setBedrockStatus] = useState<BedrockStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [openAction, setOpenAction] = useState<OpenAction | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchBedrockStatus()
      .then((status) => {
        if (!cancelled) setBedrockStatus(status);
      })
      .catch(() => {
        if (!cancelled) setBedrockStatus(null);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const load = useCallback(
    async (refresh: boolean) => {
      setError(null);
      if (refresh) setRefreshing(true);
      else setLoading(true);
      try {
        setInsights(await fetchCustomerInsights(customerId, { refresh }));
      } catch (e) {
        setError(e instanceof Error ? e.message : "Could not load insights");
      } finally {
        setLoading(false);
        setRefreshing(false);
      }
    },
    [customerId],
  );

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const data = await fetchCustomerInsights(customerId);
        if (!cancelled) setInsights(data);
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Could not load insights");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [customerId]);

  const focusLabel =
    insights?.primary_focus === "retention" ? "Retention focus" : "Upsell focus";

  const actionMeta = insights?.recommendation_actions ?? [];
  const fromBedrock = insights?.source === "bedrock";
  const subtitle = insightSubtitle(insights, bedrockStatus, loading);

  return (
    <>
      <section className="panel insights-panel">
        <div className="panel-head">
          <div>
            <h2>AI customer insights</h2>
            <p className="muted small insights-subtitle">{subtitle}</p>
          </div>
          <div className="toolbar">
            <button
              type="button"
              className="btn secondary"
              disabled={loading || refreshing}
              onClick={() => load(true)}
            >
              {refreshing ? "Refreshing…" : "Refresh insights"}
            </button>
          </div>
        </div>

        {loading && !insights && (
          <p className="muted">
            {bedrockStatus?.configured ? "Waiting for Bedrock…" : "Loading advisor insights…"}
          </p>
        )}
        {error && <p className="error">{error}</p>}

        {insights && (
          <>
            <div className="insights-meta">
              <span
                className={
                  fromBedrock ? "source-badge source-bedrock" : "source-badge source-local"
                }
              >
                {fromBedrock ? "Powered by Amazon Bedrock" : "Local advisor"}
              </span>
              <span
                className={
                  insights.primary_focus === "retention"
                    ? "focus-badge retention"
                    : "focus-badge upsell"
                }
              >
                {focusLabel}
              </span>
              {churnTier && (
                <span className="muted small">Churn tier: {churnTier}</span>
              )}
              {fromBedrock && insights.model_id && (
                <span className="muted small" title="Bedrock model ID">
                  Model: {insights.model_id}
                </span>
              )}
              {insights.cached && (
                <span className="muted small">Cached copy</span>
              )}
              {insights.generated_at && (
                <span className="muted small">Generated: {insights.generated_at}</span>
              )}
            </div>

            <p className="insights-summary">{insights.summary}</p>

            <h3 className="insights-subhead">Recommended actions</h3>
            <ul className="insights-list">
              {insights.recommendations.map((item, idx) => {
                const meta = actionMeta[idx];
                const actionable = meta?.actionable ?? false;
                return (
                  <li key={item}>
                    {actionable ? (
                      <button
                        type="button"
                        className="insight-action-link"
                        onClick={() =>
                          setOpenAction({ recommendation: item, source: "recommendation" })
                        }
                      >
                        {item}
                      </button>
                    ) : (
                      item
                    )}
                  </li>
                );
              })}
            </ul>

            {insights.experience_note && (
              <p className="insights-note">
                <span className="label">Best next touch</span>
                {insights.experience_note_actionable ? (
                  <button
                    type="button"
                    className="insight-action-link inline"
                    onClick={() =>
                      setOpenAction({
                        recommendation: insights.experience_note!,
                        source: "experience_note",
                      })
                    }
                  >
                    {insights.experience_note}
                  </button>
                ) : (
                  insights.experience_note
                )}
              </p>
            )}

            {!fromBedrock && !insights.bedrock_configured && (
              <p className="muted small insights-hint">
                To enable Bedrock-generated text, set <code>AWS_ACCESS_KEY_ID</code>,{" "}
                <code>AWS_SECRET_ACCESS_KEY</code>, and optional{" "}
                <code>CUSTOMER360_BEDROCK_MODEL_ID</code> (see <code>.env.example</code>).
              </p>
            )}
          </>
        )}
      </section>

      {openAction && (
        <InsightActionModal
          customerId={customerId}
          recommendation={openAction.recommendation}
          source={openAction.source}
          onClose={() => setOpenAction(null)}
        />
      )}
    </>
  );
}
